# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - StrapiOnAzure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://strapionazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_005156721bfa4b4dad10009cd3e8de4d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1b8e4451b8a043be9faa037d06cbd341 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: strapionazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_005156721bfa4b4dad10009cd3e8de4d }}/strapionazure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'StrapiOnAzure'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d56710f41aac49c2ad59c2f7e779e9be }}
        images: 'strapionazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_005156721bfa4b4dad10009cd3e8de4d }}/strapionazure:${{ github.sha }}'